[package]
name = "owos_6502"
version = "0.1.0"
authors = ["jenra <jenra.uwu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emulator_6502 = "1.0.0"
ncurses = "5.99.0"
